### ISSUE TITLE
Database error: "zerver_realmfilter does not exist at character 146"

### ISSUE THREAD

**Issue by decker502** [Galexrt/docker-zulip#34]
Hi @Galexrt ,

Zulip can't work When I follow the below 

> You can add your certificate in the certs directory at the volumes mount point, for example by default > /opt/docker/zulip/zulip/, the certificates folder would be at /opt/docker/zulip/zulip/certs.

## database'log output:

```
database_1 | 2015-10-23 03:22:52 UTC [10242-1] zulip@zulip ERROR:  relation "zerver_scheduledjob" does not exist at character 219
database_1 | 2015-10-23 03:22:52 UTC [10242-2] zulip@zulip STATEMENT:  SELECT "zerver_scheduledjob"."id", "zerver_scheduledjob"."scheduled_timestamp", "zerver_scheduledjob"."type", "zerver_scheduledjob"."data", "zerver_scheduledjob"."filter_id", "zerver_scheduledjob"."filter_string" FROM "zerver_scheduledjob" WHERE ("zerver_scheduledjob"."type" = 1 AND "zerver_scheduledjob"."scheduled_timestamp" <= '2015-10-23T03:22:52.077736-04:00'::timestamptz)
database_1 | 2015-10-23 03:22:52 UTC [10243-1] zulip@zulip ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1 | 2015-10-23 03:22:52 UTC [10243-2] zulip@zulip STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1 | 2015-10-23 03:22:52 UTC [10244-1] zulip@zulip ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1 | 2015-10-23 03:22:52 UTC [10244-2] zulip@zulip STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1 | 2015-10-23 03:22:52 UTC [10245-1] zulip@zulip ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1 | 2015-10-23 03:22:52 UTC [10245-2] zulip@zulip STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"

```

## zulip's log output :  

```
zulip_1 | 2015-10-23 03:00:52,901 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-message_sender-4 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-message_sender-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-message_sender-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-message_sender-2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-message_sender-3 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-error_reports entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-user-presence entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-deliver-enqueued-emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-slowqueries entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-email_mirror entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,902 INFO success: zulip-events-user-activity-interval entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-confirmation-emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-missedmessage_mobile_notifications entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-signups entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-digest_emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-missedmessage_reminders entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-user-activity entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:52,910 INFO success: zulip-events-feedback_messages entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1 | 2015-10-23 03:00:53,224 INFO exited: process-fts-updates (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:53,319 INFO exited: zulip-deliver-enqueued-emails (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:53,844 INFO spawned: 'zulip-deliver-enqueued-emails' with pid 362
zulip_1 | 2015-10-23 03:00:54,012 INFO exited: zulip-events-feedback_messages (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,033 INFO spawned: 'zulip-events-feedback_messages' with pid 363
zulip_1 | 2015-10-23 03:00:54,034 INFO exited: zulip-events-missedmessage_reminders (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,040 INFO spawned: 'zulip-events-missedmessage_reminders' with pid 364
zulip_1 | 2015-10-23 03:00:54,041 INFO exited: zulip-events-message_sender-4 (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,046 INFO spawned: 'zulip-events-message_sender-4' with pid 365
zulip_1 | 2015-10-23 03:00:54,048 INFO exited: zulip-events-message_sender-2 (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,077 INFO spawned: 'zulip-events-message_sender-2' with pid 366
zulip_1 | 2015-10-23 03:00:54,078 INFO exited: zulip-events-slowqueries (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,090 INFO spawned: 'zulip-events-slowqueries' with pid 368
zulip_1 | 2015-10-23 03:00:54,092 INFO exited: zulip-events-digest_emails (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,119 INFO spawned: 'zulip-events-digest_emails' with pid 369
zulip_1 | 2015-10-23 03:00:54,122 INFO exited: zulip-events-email_mirror (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,127 INFO spawned: 'zulip-events-email_mirror' with pid 371
zulip_1 | 2015-10-23 03:00:54,127 INFO exited: zulip-tornado (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,130 INFO spawned: 'zulip-tornado' with pid 372
zulip_1 | 2015-10-23 03:00:54,132 INFO exited: zulip-events-message_sender-3 (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,133 INFO exited: zulip-events-missedmessage_mobile_notifications (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,141 INFO spawned: 'zulip-events-message_sender-3' with pid 373
zulip_1 | 2015-10-23 03:00:54,144 INFO spawned: 'zulip-events-missedmessage_mobile_notifications' with pid 374
zulip_1 | 2015-10-23 03:00:54,158 INFO exited: zulip-events-error_reports (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,167 INFO spawned: 'zulip-events-error_reports' with pid 375
zulip_1 | 2015-10-23 03:00:54,168 INFO exited: zulip-events-user-activity (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,175 INFO spawned: 'zulip-events-user-activity' with pid 376
zulip_1 | 2015-10-23 03:00:54,176 INFO exited: zulip-events-user-presence (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,176 INFO exited: zulip-events-confirmation-emails (exit status 1; not expected)
zulip_1 | 2015-10-23 03:00:54,195 INFO spawned: 'zulip-events-user-presence' with pid 377
zulip_1 | 2015-10-23 03:00:54,197 INFO spawned: 'zulip-events-confirmation-emails' with pid 378
zulip_1 | 2015-10-23 03:00:54,201 INFO exited: zulip-events-message_sender-0 (exit status 1; not expected)
```

## ```events-message_sender.log``` in container

```
Traceback (most recent call last):
  File "/home/zulip/deployments/current/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/management/commands/process_queue.py", line 6, in <module>
    from zerver.worker.queue_processors import get_worker
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/worker/queue_processors.py", line 13, in <module>
    from zerver.lib.actions import do_send_confirmation_email, \
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/lib/actions.py", line 41, in <module>
    from zerver.lib import bugdown
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/lib/bugdown/__init__.py", line 1028, in <module>
    maybe_update_realm_filters(domain=None)
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/lib/bugdown/__init__.py", line 1016, in maybe_update_realm_filters
    all_filters = all_realm_filters()
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/models.py", line 260, in all_realm_filters
    for realm_filter in RealmFilter.objects.all():
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 977, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/lib/db.py", line 23, in execute
    return wrapper_execute(self, super(TimeTrackingCursor, self).execute, query, vars)
  File "/home/zulip/deployments/2015-10-22-19-21-40/zerver/lib/db.py", line 11, in wrapper_execute
    return action(sql, params)
django.db.utils.ProgrammingError: relation "zerver_realmfilter" does not exist
LINE 1: ...n", "zerver_realmfilter"."url_format_string" FROM "zerver_re...

```

## ```fts-updates.log``` in container

```
2015-10-23 03:00:51,534 INFO: process_fts_updates starting
2015-10-23 03:00:51,547 INFO: Not in recovery; listening for FTS updates
Traceback (most recent call last):
  File "/usr/local/bin/process_fts_updates", line 45, in <module>
    update_fts_columns(cursor)
  File "/usr/local/bin/process_fts_updates", line 9, in update_fts_columns
    cursor.execute("SELECT id, message_id FROM fts_update_log;")
psycopg2.ProgrammingError: relation "fts_update_log" does not exist
LINE 1: SELECT id, message_id FROM fts_update_log;
                                   ^

2015-10-23 03:00:53,212 INFO: process_fts_updates starting
2015-10-23 03:00:53,217 INFO: Not in recovery; listening for FTS updates
Traceback (most recent call last):
  File "/usr/local/bin/process_fts_updates", line 45, in <module>
    update_fts_columns(cursor)
  File "/usr/local/bin/process_fts_updates", line 9, in update_fts_columns
    cursor.execute("SELECT id, message_id FROM fts_update_log;")
psycopg2.ProgrammingError: relation "fts_update_log" does not exist
LINE 1: SELECT id, message_id FROM fts_update_log;
                                   ^

2015-10-23 03:00:55,697 INFO: process_fts_updates starting
2015-10-23 03:00:55,702 INFO: Not in recovery; listening for FTS updates
Traceback (most recent call last):
  File "/usr/local/bin/process_fts_updates", line 45, in <module>
    update_fts_columns(cursor)
  File "/usr/local/bin/process_fts_updates", line 9, in update_fts_columns
    cursor.execute("SELECT id, message_id FROM fts_update_log;")
psycopg2.ProgrammingError: relation "fts_update_log" does not exist
LINE 1: SELECT id, message_id FROM fts_update_log;
                                   ^

2015-10-23 03:00:59,131 INFO: process_fts_updates starting
2015-10-23 03:00:59,141 INFO: Not in recovery; listening for FTS updates
Traceback (most recent call last):
  File "/usr/local/bin/process_fts_updates", line 45, in <module>
    update_fts_columns(cursor)
  File "/usr/local/bin/process_fts_updates", line 9, in update_fts_columns
    cursor.execute("SELECT id, message_id FROM fts_update_log;")
psycopg2.ProgrammingError: relation "fts_update_log" does not exist
LINE 1: SELECT id, message_id FROM fts_update_log;
```

**Comment by Galexrt** [comment]
@decker502 Could you provide the image id?
I think this happens, because of a "failed" Zulip database migration. When I have the image id, I can give you more help.

**Comment by Galexrt** [comment]
@decker502 I updated the wiki page for ssl configuration.
The error you are having isn't related to the ssl certs.
The error is seems to be an problem with the tables in the database.
Can you try to clear all volume folders from zulip and the database and start it up again.

BTW I'm currently on the IRC.

**Comment by decker502** [comment]
@Galexrt The images id is 4986116b2c48.

 > Can you try to clear all volume folders from zulip and the database and start it up again

I have tried it first time when I met the error.
If I clear all volume folders it works well. But if I clear all folders  expect certs folder ,  I will get error.

**Comment by Galexrt** [comment]
@decker502 Have you checked the updated wiki page for it? I added how the certificate file names have to be.

Could you run the container with `docker-compose` and stop it after it started and do a `find /opt/docker/zulip/zulip` (replace `/opt/docker/zulip/zulip` with your actual host volume path and then  please post the output here.

**Comment by decker502** [comment]
@Galexrt 
## the output:

```
[root@localhost docker-zulip]# find /home/app/zulip/zulip
/home/app/zulip/zulip
/home/app/zulip/zulip/uploads
/home/app/zulip/zulip/uploads/uploads
/home/app/zulip/zulip/certs
/home/app/zulip/zulip/certs/zulip.combined-chain.crt
/home/app/zulip/zulip/certs/zulip.key
/home/app/zulip/zulip/zulip-settings.py
/home/app/zulip/zulip/.zulip-1.3.7
/home/app/zulip/zulip/.initiated
/home/app/zulip/zulip/zulip-secrets.conf

```

**Comment by Galexrt** [comment]
Issue resolved in IRC.

**Comment by shilov** [comment]
Got the same problem. Would love to know how to fix this.

**Comment by Galexrt** [comment]
@shilov Please create a new ticket with your logs, so I can look at it. Thanks.
